### ISSUE TITLE
having issues getting matchup stats in NBA Fantasy

### ISSUE THREAD

**Issue by prestonlam53** [mattdodge/yahoofantasy#47]
Hi Matt,

Trying to get matchup stats while playing 9cat NBA Fantasy. The idea is to be able to compare my weekly stats across the board, not just against my current matchup. 

Currently using this line of code:
for week in league.weeks():
    matchups = week.matchups
    for matchup in matchups:
        print(week)
        print(f"{matchup.team1.name}\tvs\t{matchup.team2.name}")
        print(matchup.team1_stats)

I'm getting an error when trying to retrieve matchup.team1_stats - Stat ID 9004003 not found in mlb stats

This doesn't make sense to me because I'm not playing MLB. is there a way around this? Should I be manually entering in which stats I want to capture / which ones to avoid?

Thanks

**Comment by mattdodge** [comment]
This is indeed a bug, there's a [TODO in the code](https://github.com/mattdodge/yahoofantasy/blob/7620f798eacc22e6b15a1f34822c5dddcd8fc52d/yahoofantasy/stats/stat.py#L20) to fix this too in fact.

The stat values from the matchup objects are hard-coded to MLB right now. If you get the stats from the player object it should work ok though. I can work on a fix for this bug later this week, but in the meantime something along these lines should get you closer

```python
def matchup_team_stats(matchup, team_num):
  team = matchup.teams.team[team_num]
  return [Stat.from_value(d, 'nba') for d in team.team_stats.stats.stat]

for week in league.weeks():
  matchups = week.matchups
  for matchup in matchups:
    print(week)
    print(f"{matchup.team1.name}\tvs\t{matchup.team2.name}")
    print(matchup_team_stats(matchup, 0))
    print(matchup_team_stats(matchup, 1))
```

**Comment by mattdodge** [comment]
This should also now be fixed in version 1.3.1 (`pip install -U yahoofantasy` to get the latest version). I'm not seeing that stat ID (9004003) in the list of valid NBA stats though so let me know if this actually ends up working

**Comment by prestonlam53** [comment]
i upgraded yahoofantasy and also tried the code you wrote. still getting the same error:

Traceback (most recent call last):
  File "fantasy_downloads.py", line 57, in <module>
    print(matchup_team_stats(matchup, 0))
  File "fantasy_downloads.py", line 50, in matchup_team_stats
    return [Stat.from_value(d, 'nba') for d in team.team_stats.stats.stat]
  File "fantasy_downloads.py", line 50, in <listcomp>
    return [Stat.from_value(d, 'nba') for d in team.team_stats.stats.stat]
  File "/Users/plam1122/opt/anaconda3/envs/metis/lib/python3.8/site-packages/yahoofantasy/stats/stat.py", line 21, in from_value
    return get_stat_from_value(d, game)
  File "/Users/plam1122/opt/anaconda3/envs/metis/lib/python3.8/site-packages/yahoofantasy/stats/utils.py", line 22, in get_stat_from_value
    raise ValueError(
ValueError: Stat ID 9004003 not found in nba stats

**Comment by mattdodge** [comment]
Yeah I'm not seeing that stat ID `9004003` in the list of stats. The format doesn't even remotely match the format of [the other stat IDs](https://github.com/mattdodge/yahoofantasy/blob/master/yahoofantasy/stats/nba.py). I'm not in an NBA fantasy league so it's hard for me to reproduce on my end. Can you tell what stat that might be referencing?

Try printing out `team.team_stats.stats.stat` and see what it looks like. You may just need to handle that exception and move on if there's one or two rogue stat IDs in that list for some reason.

**Comment by BenCo82** [comment]
hello,

stat 9004003 is field goal made / field goal attempted ratio, there is also another stat with same kind of idea 9007006 which is free throw made / free throw attempted.
Solved the issue by adding those in dict stats of nba.py

thanks for the package

**Comment by prestonlam53** [comment]
i was able to fix this issue by printing out team.team_stats.stats.stat and manually assigning stat names as a dictionary. haven't tried to incorporate nba.py yet.

**Comment by mattdodge** [comment]
Looks like the `/game/nba/stat_categories` API endpoint on Yahoo isn't returning the full list of stats. Strange. I'll add these two known stats to the list and will probably try to make the library a bit more fault tolerant for missing stats like this since it seems like it can happen. Thanks for flagging!

**Comment by xaph** [comment]
hello @mattdodge 

I have fixed this problem and send with a PR:
https://github.com/mattdodge/yahoofantasy/pull/64

I'm working on my own copy. It would be great if you merge the request and create a new version.

**Comment by mattdodge** [comment]
Thanks! Fixed in 1.4.3
